var rawData = {
  "pagination": {
    "page": 1,
    "pages": 200,
    "per_page": 50,
    "items": 4562087,
    "urls": {
      "last": "https://api.discogs.com/database/search?q=pop&key=ndqiGGFVIuiLYHmjQExU&secret=ADOGBtMyjsEJjQkyVcoNQTASKAuLfdCW&page=200&per_page=50",
      "next": "https://api.discogs.com/database/search?q=pop&key=ndqiGGFVIuiLYHmjQExU&secret=ADOGBtMyjsEJjQkyVcoNQTASKAuLfdCW&page=2&per_page=50"
    }
  },
  "results": [
    {
      "id": 11073,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/11073-Iggy-Pop",
      "title": "Iggy Pop",
      "thumb": "https://i.discogs.com/yhw0UbzUk1q6jDilVmAQWudz4FrFUjjjQdNs2pWA53s/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTExMDcz/LTE2MjA0MDkyNDMt/NjA2MC5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/U_IEXIkn7aLQsV2-mHCRrqrNl-rcy7w1h4U8R8tc8SA/rs:fit/g:sm/q:90/h:850/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTExMDcz/LTE2MjA0MDkyNDMt/NjA2MC5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/artists/11073"
    },
    {
      "id": 77343,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/77343-Sub-Pop",
      "title": "Sub Pop",
      "thumb": "https://i.discogs.com/TQ05zEo7pCJ-0LuFBiYpU58JjU_JWqbNvtgPVAUqPIs/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTc3MzQz/LTE0OTk4ODY3MDMt/MTMxNy5wbmc.jpeg",
      "cover_image": "https://i.discogs.com/YcKuQsbfZYLesLodt2DTlAX3HmCCOJSZsmEjaQ7DCd0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTc3MzQz/LTE0OTk4ODY3MDMt/MTMxNy5wbmc.jpeg",
      "resource_url": "https://api.discogs.com/labels/77343"
    },
    {
      "id": 57613,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/57613-Denniz-Pop",
      "title": "Denniz Pop",
      "thumb": "https://i.discogs.com/H_HsuykRiLplpvKN0DE1oZkZNHQHeFOhOE2Zk_7ReyU/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTU3NjEz/LTEwOTQ4MjI0MzMu/anBn.jpeg",
      "cover_image": "https://i.discogs.com/z7zxbh1FL9PuHbAklftvCxlMMt7HH4-BckXroBI5Cyw/rs:fit/g:sm/q:90/h:246/w:168/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTU3NjEz/LTEwOTQ4MjI0MzMu/anBn.jpeg",
      "resource_url": "https://api.discogs.com/artists/57613"
    },
    {
      "country": "Europe",
      "year": "1997",
      "format": ["CD", "Album"],
      "label": [
        "Island Records",
        "Island Records",
        "PolyGram International Music B.V.",
        "PolyGram International Music B.V.",
        "Island Records Ltd.",
        "PMDC, Germany",
        "PolyGram International Music Publishing B.V.",
        "Blue Mountain Music Ltd.",
        "Mother Music Ltd.",
        "Hanover Quay Studios",
        "Windmill Lane Studios",
        "South Beach Studios",
        "The Works, Dublin",
        "Masterdisk",
        "ABA, Dublin"
      ],
      "type": "master",
      "genre": ["Electronic", "Rock"],
      "style": ["Pop Rock", "Synth-pop", "Experimental"],
      "id": 62553,
      "barcode": [
        "7 31452 43342 8",
        "731452433428",
        "LC 0407",
        "PY811",
        "BIEM/MCPS",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BE",
        "IFPI L003",
        "IFPI 01K9",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AZ",
        "IFPI L003",
        "IFPI 01K6",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BK",
        "IFPI L003",
        "IFPI 01RS",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AU",
        "IFPI L003",
        "IFPI 01L3",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BL",
        "IFPI L003",
        "IFPI 01N4",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AS",
        "IFPI L003",
        "IFPI 01K6",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BI",
        "IFPI L003",
        "IFPI 01L3",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BD",
        "IFPI L003",
        "IFPI 01K9",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AX",
        "IFPI L003",
        "IFPI 01K7",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BB",
        "IFPI L003",
        "IFPI 01N4",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BH",
        "IFPI L003",
        "IFPI 01K6",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BL",
        "IFPI L003",
        "IFPI 01K7",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AW",
        "IFPI L003",
        "IFPI 01N5",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC  AT",
        "IFPI L003",
        "IFPI 01R5",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BM",
        "IFPI L003",
        "IFPI 01R5",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AZ",
        "IFPI L003",
        "IFPI 01R4",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BK",
        "IFPI L003",
        "IFPI 01L3"
      ],
      "master_id": 62553,
      "master_url": "https://api.discogs.com/masters/62553",
      "uri": "/master/62553-U2-Pop",
      "catno": "CIDU210",
      "title": "U2 - Pop",
      "thumb": "https://i.discogs.com/qoEQWIdMYHCr_H3X_TUtBPSGQZOxpvn6GtzpyJqwmsg/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNzEz/MC0xNjA1OTQzNTc5/LTQ0MTAuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/TQ8_kl1zmIcZTb6r_Qqybr9sWoJs5BY6AEL99xUApYc/rs:fit/g:sm/q:90/h:601/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNzEz/MC0xNjA1OTQzNTc5/LTQ0MTAuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/masters/62553",
      "community": { "want": 6518, "have": 26699 }
    },
    {
      "id": 5131,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/5131-Sub-Pop-Records",
      "title": "Sub Pop Records",
      "thumb": "",
      "cover_image": "https://st.discogs.com/86cc1f5820fbf8d2cf42e884012d199c7057e72a/images/spacer.gif",
      "resource_url": "https://api.discogs.com/labels/5131"
    },
    {
      "id": 233954,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/233954-Pop-5",
      "title": "Pop (5)",
      "thumb": "",
      "cover_image": "https://st.discogs.com/86cc1f5820fbf8d2cf42e884012d199c7057e72a/images/spacer.gif",
      "resource_url": "https://api.discogs.com/artists/233954"
    },
    {
      "id": 25773,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/25773-Pop",
      "title": "Pop",
      "thumb": "https://i.discogs.com/8wqZHp50moJsqrAbdm2MaK5ttih359EkWimrgTOWptE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTI1Nzcz/LTEzNjQwNjg2ODkt/OTQ3Ny5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/RU_-Pqh5I0trqyCdkudNjnJS3jUDCTw2lYPzSUOTLNI/rs:fit/g:sm/q:90/h:209/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTI1Nzcz/LTEzNjQwNjg2ODkt/OTQ3Ny5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/labels/25773"
    },
    {
      "id": 2021820,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/2021820-Pop-Wansel",
      "title": "Pop Wansel",
      "thumb": "https://i.discogs.com/003cvt00tpokl1TJOVgOu4p0JdRCstALIhL6tjpdJxE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIwMjE4/MjAtMTQyNDY3ODI2/MS03NTE1LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/tOrTuvCkrpR0mS_7gyR-za2ozytBQesic-R4d8cGyMw/rs:fit/g:sm/q:90/h:594/w:475/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIwMjE4/MjAtMTQyNDY3ODI2/MS03NTE1LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/2021820"
    },
    {
      "country": "US",
      "year": "2016",
      "format": ["Vinyl", "LP", "Album"],
      "label": [
        "Loma Vista",
        "Rekords Rekords",
        "IGHO, LLC",
        "IGHO, LLC",
        "Loma Vista Recordings",
        "Concord Music Group, Inc.",
        "Concord Music Group, Inc.",
        "Pallas USA",
        "Pallas",
        "Lurssen Mastering",
        "Top Notch Booty",
        "BMG Rights Management",
        "Board Stuff Music",
        "Sleeping Disorder Music",
        "Songs Of Kobalt Music Publishing",
        "Rancho De La Luna",
        "Pink Duck Studios",
        "United Recording Studios",
        "Pink Duck Studios"
      ],
      "type": "master",
      "genre": ["Rock"],
      "style": [],
      "id": 973103,
      "barcode": [
        "888072390881",
        "LVR-39088-01-A CB P.USA -38585-",
        "LVR-39088-01-B CB -38585- P.USA",
        "BMI"
      ],
      "master_id": 973103,
      "master_url": "https://api.discogs.com/masters/973103",
      "uri": "/master/973103-Iggy-Pop-Post-Pop-Depression",
      "catno": "LVR-39088-01",
      "title": "Iggy Pop - Post Pop Depression",
      "thumb": "https://i.discogs.com/3x3hNmdG8UoVJQAY2G3SYZCPjmD7HKIidXASOD83dbI/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyNjA1/MDAtMTQ1ODkzNDE1/Ny0zMTM2LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/UbRwgpqzU6pBBHB3Ma-3mcqIPczqk_w_c0Fc8ZyGBO8/rs:fit/g:sm/q:90/h:601/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyNjA1/MDAtMTQ1ODkzNDE1/Ny0zMTM2LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/masters/973103",
      "community": { "want": 2407, "have": 15287 }
    },
    {
      "country": "UK",
      "year": "1984",
      "format": ["Vinyl", "LP", "Album", "Stereo"],
      "label": [
        "Beggars Banquet",
        "Beggars Banquet",
        "Beggars Banquet",
        "Beggars Banquet Music Ltd.",
        "Rockfield Studios",
        "Beck Studios",
        "R.G. Jones Studios",
        "Musitech",
        "Damont",
        "WEA Records Ltd.",
        "Warner Communications"
      ],
      "type": "master",
      "genre": ["Electronic", "Rock"],
      "style": ["Goth Rock", "Pop Rock", "Synth-pop"],
      "id": 61639,
      "barcode": [
        "BEGA 51 A",
        "BEGA 51 B",
        "BEGA-51-A1. DAMONT MT.5",
        "BEGA-51-B1. DAMONT MT 5",
        "BEGA-51-A1. DAMONT MT. GA",
        "BEGA-51-B1. DAMONT MT. KA",
        "BEGA-51-A1. DAMONT MT. F",
        "BEGA-51-B1. DAMONT MT. I",
        "BEGA-51-A1. \u295f DAMONT 1 MT. E",
        "BEGA-51-B1. - DAMONT MT. J"
      ],
      "master_id": 61639,
      "master_url": "https://api.discogs.com/masters/61639",
      "uri": "/master/61639-Tones-On-Tail-Pop",
      "catno": "BEGA 51",
      "title": "Tones On Tail - Pop",
      "thumb": "https://i.discogs.com/Bf-bADbFS-oZf9hm8ghFUEa9fz5yI9YpoGgqX48otl8/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwNzU2/Ni0xMzc3MzAwNzUz/LTkxNjkuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/sZ_BHvZIYV07KWzTIZLhTq596pLCHb3r1ZqRjILyF1c/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwNzU2/Ni0xMzc3MzAwNzUz/LTkxNjkuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/masters/61639",
      "community": { "want": 2827, "have": 4322 }
    },
    {
      "country": "Germany",
      "year": "2000",
      "format": ["CD", "Album"],
      "label": ["Mille Plateaux", "EFA", "Blei", "MPO"],
      "type": "master",
      "genre": ["Electronic"],
      "style": ["Modern Classical", "Techno", "Ambient"],
      "id": 14307,
      "barcode": [
        "7 18750 80832 5",
        "718750808325",
        "MP 83 MPO 01 @@@ 4",
        "01",
        "03",
        "IFPI L033",
        "IFPI 1225",
        "IFPI 1227",
        "IFPI 1216",
        "IFPI 122B",
        "LC 10521",
        "GEMA"
      ],
      "master_id": 14307,
      "master_url": "https://api.discogs.com/masters/14307",
      "uri": "/master/14307-Gas-Pop",
      "catno": "MPCD 83",
      "title": "Gas - Pop",
      "thumb": "https://i.discogs.com/86R6grKXRst-nGw4odtyuEvAJwEvU7wIPqjHcri7cjs/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM1NzA5/LTExNjQ5NDA3MjEu/anBlZw.jpeg",
      "cover_image": "https://i.discogs.com/1m0VMNV_GzySdnAMgND6x5s_Hv8LdJLm4FTXSBMmzI0/rs:fit/g:sm/q:90/h:587/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM1NzA5/LTExNjQ5NDA3MjEu/anBlZw.jpeg",
      "resource_url": "https://api.discogs.com/masters/14307",
      "community": { "want": 3160, "have": 2025 }
    },
    {
      "id": 165662,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/165662-Jimmy-Pop",
      "title": "Jimmy Pop",
      "thumb": "https://i.discogs.com/mxs1F9k1HyMR17wm3V6Q4sWvQDvQZM1Dn8t5fj6Wuxc/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE2NTY2/Mi0xNjUyOTU0MDA2/LTMzNzIuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/NsTb0gx5DtAPJWUFjiZJMmc6kevdEbgo08hhi2ALw44/rs:fit/g:sm/q:90/h:450/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE2NTY2/Mi0xNjUyOTU0MDA2/LTMzNzIuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/artists/165662"
    },
    {
      "id": 194365,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/194365-Mom-Pop",
      "title": "Mom + Pop",
      "thumb": "https://i.discogs.com/4NyrSCTfQGmWUaaL112CBNVVWiPKFDrx1EdPBGlxPbM/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTE5NDM2/NS0xNDk3NTIwNzk2/LTk4NjguanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/MnnbHjLKHfKTTvpasuaNHR32_VbC6-EnGRW_mR7sO7U/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTE5NDM2/NS0xNDk3NTIwNzk2/LTk4NjguanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/labels/194365"
    },
    {
      "country": "Europe",
      "year": "2018",
      "format": ["Vinyl", "LP", "Album", "Reissue", "Remastered"],
      "label": [
        "Island Records",
        "Island Records",
        "UMC",
        "UMC",
        "Hanover Quay Studios",
        "Windmill Lane Studios",
        "South Beach Studios",
        "The Works, Dublin",
        "Masterdisk",
        "ABA, Dublin",
        "Universal Music",
        "Universal Music Operations Ltd.",
        "Universal Music Operations Ltd.",
        "Bernie Grundman Mastering",
        "Bernie Grundman Mastering",
        "Optimal Media GmbH"
      ],
      "type": "release",
      "genre": ["Electronic", "Rock"],
      "style": ["Pop Rock", "Synth-pop", "Experimental"],
      "id": 11846879,
      "barcode": [
        "LC 0407",
        "BIEM/SDRM",
        "0602557969993",
        "6 02557 96999 3",
        "BH11770-01 A1 5796999-A1 CB/SS",
        "BH11770-01 B1 5796999-B1 CB/SS",
        "BH11770-02 C1 5796999-C1 CB/SS",
        "BH11770-02 D1 5796999-D1 CB/SS"
      ],
      "master_id": 62553,
      "master_url": "https://api.discogs.com/masters/62553",
      "uri": "/release/11846879-U2-Pop",
      "catno": "U2 10",
      "title": "U2 - Pop",
      "thumb": "https://i.discogs.com/i54SSL5CqfXPm05AWaJa-OST9pMs9MPFGqJe73lBB4E/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExODQ2/ODc5LTE1MjM2Mzc4/NjAtMTg3NC5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/0TQh4ttLINzqRnUoycuFVLQjM0499Ps820bgsQipvS0/rs:fit/g:sm/q:90/h:589/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExODQ2/ODc5LTE1MjM2Mzc4/NjAtMTg3NC5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/releases/11846879",
      "community": { "want": 393, "have": 4018 },
      "format_quantity": 2,
      "formats": [
        {
          "name": "Vinyl",
          "qty": "2",
          "text": "180g",
          "descriptions": ["LP", "Album", "Reissue", "Remastered"]
        }
      ]
    },
    {
      "country": "Europe",
      "year": "2001",
      "format": ["CD", "Single"],
      "label": [
        "Jive",
        "Zomba Recording Corporation",
        "Zomba Recording Corporation",
        "4 Box Studios",
        "4 Box Studios",
        "Westlake Audio",
        "Metalworks Studios",
        "Battery Studios, New York",
        "Battery Mastering Studios",
        "Sony DADC"
      ],
      "type": "master",
      "genre": ["Pop"],
      "style": ["Europop"],
      "id": 73070,
      "barcode": [
        "6 38592 52289 3",
        "638592522893",
        "MCPS/BIEM/STEMRA/GEMA/NCB/SDRM/SIAE/SGAE",
        "LC 07925",
        "Sony DADC A0100370779-0101 14 A0",
        "IFPI L554",
        "IFPI 94K6"
      ],
      "master_id": 73070,
      "master_url": "https://api.discogs.com/masters/73070",
      "uri": "/master/73070-NSYNC-Pop",
      "catno": "9252289",
      "title": "*NSYNC - Pop",
      "thumb": "https://i.discogs.com/b9EaBKKeBs2KXMbGtIGXkgSSgk7PD2tHn0QrZPlaLHY/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNzYy/MzktMTE5ODQzNDcx/MS5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/xETKJ6-20OE5nwAGP1L9ZNTbrw3d4U2ldc8JHIyN06U/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNzYy/MzktMTE5ODQzNDcx/MS5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/masters/73070",
      "community": { "want": 584, "have": 992 }
    },
    {
      "country": "Europe",
      "year": "1997",
      "format": ["CD", "Album"],
      "label": [
        "Island Records",
        "Island Records",
        "PolyGram International Music B.V.",
        "PolyGram International Music B.V.",
        "Island Records Ltd.",
        "PMDC, Germany",
        "PolyGram International Music Publishing B.V.",
        "Blue Mountain Music Ltd.",
        "Mother Music Ltd.",
        "Hanover Quay Studios",
        "Windmill Lane Studios",
        "South Beach Studios",
        "The Works, Dublin",
        "Masterdisk",
        "ABA, Dublin"
      ],
      "type": "release",
      "genre": ["Electronic", "Rock"],
      "style": ["Pop Rock", "Synth-pop", "Experimental"],
      "id": 137130,
      "barcode": [
        "7 31452 43342 8",
        "731452433428",
        "LC 0407",
        "PY811",
        "BIEM/MCPS",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BE",
        "IFPI L003",
        "IFPI 01K9",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AZ",
        "IFPI L003",
        "IFPI 01K6",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BK",
        "IFPI L003",
        "IFPI 01RS",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AU",
        "IFPI L003",
        "IFPI 01L3",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BL",
        "IFPI L003",
        "IFPI 01N4",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AS",
        "IFPI L003",
        "IFPI 01K6",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BI",
        "IFPI L003",
        "IFPI 01L3",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BD",
        "IFPI L003",
        "IFPI 01K9",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AX",
        "IFPI L003",
        "IFPI 01K7",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BB",
        "IFPI L003",
        "IFPI 01N4",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BH",
        "IFPI L003",
        "IFPI 01K6",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BL",
        "IFPI L003",
        "IFPI 01K7",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AW",
        "IFPI L003",
        "IFPI 01N5",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC  AT",
        "IFPI L003",
        "IFPI 01R5",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BM",
        "IFPI L003",
        "IFPI 01R5",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC AZ",
        "IFPI L003",
        "IFPI 01R4",
        "524 334-2 02 > 4UALKXXXX MADE IN GERMANY BY PMDC BK",
        "IFPI L003",
        "IFPI 01L3"
      ],
      "master_id": 62553,
      "master_url": "https://api.discogs.com/masters/62553",
      "uri": "/release/137130-U2-Pop",
      "catno": "CIDU210",
      "title": "U2 - Pop",
      "thumb": "https://i.discogs.com/qoEQWIdMYHCr_H3X_TUtBPSGQZOxpvn6GtzpyJqwmsg/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNzEz/MC0xNjA1OTQzNTc5/LTQ0MTAuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/TQ8_kl1zmIcZTb6r_Qqybr9sWoJs5BY6AEL99xUApYc/rs:fit/g:sm/q:90/h:601/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNzEz/MC0xNjA1OTQzNTc5/LTQ0MTAuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/releases/137130",
      "community": { "want": 133, "have": 4327 },
      "format_quantity": 1,
      "formats": [{ "name": "CD", "qty": "1", "descriptions": ["Album"] }]
    },
    {
      "country": "UK",
      "year": "1979",
      "format": ["Vinyl", "7\"", "45 RPM", "Single"],
      "label": [
        "MCA Records",
        "Midascare Productions Ltd.",
        "EMI Records Ltd.",
        "EMI Records",
        "Robert Stace"
      ],
      "type": "master",
      "genre": ["Electronic"],
      "style": ["Synth-pop"],
      "id": 122037,
      "barcode": [
        "MCA 413A",
        "MCA 413B",
        "MCA 413 A-2U A BILBO BOPPA!  VU ",
        "MCA 413 B-2U BILBO CU",
        "MCA 413 A-2U 1  A BILBO BOPPA!",
        "MCA 413 B-2U 2 C A R  BILBO",
        "MCA 413 A-2U G U P  A BILBO BOPPA!  VU ",
        "MCA 413 B-2U G G P BILBO"
      ],
      "master_id": 122037,
      "master_url": "https://api.discogs.com/masters/122037",
      "uri": "/master/122037-M-Pop-Muzik",
      "catno": "MCA 413",
      "title": "M (2) - Pop Muzik",
      "thumb": "https://i.discogs.com/gJLnUNyThLvJaOOhxRdfCkJkWWOdFlIGqjrRDTnBkDY/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMjQ2/OS0xNTgxODE1NjQ1/LTE1OTIuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/wxiiBxmo-LhcYy08Dhdb9JeerDosspkDnvs91Ytp0Ts/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMjQ2/OS0xNTgxODE1NjQ1/LTE1OTIuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/masters/122037",
      "community": { "want": 5932, "have": 18529 }
    },
    {
      "country": "Germany",
      "year": "2020",
      "format": ["Vinyl", "LP", "Album", "Limited Edition", "Stereo"],
      "label": ["twoFinger Records GmbH"],
      "type": "master",
      "genre": ["Pop"],
      "style": [],
      "id": 1746862,
      "barcode": [],
      "master_id": 1746862,
      "master_url": "https://api.discogs.com/masters/1746862",
      "uri": "/master/1746862-Fynn-Kliemann-POP",
      "catno": "none",
      "title": "Fynn Kliemann - POP",
      "thumb": "https://i.discogs.com/XULVz21K4DINqj0y0m_MP-1hkw1H71R89biuGe0a4Nc/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzg5/NjQyLTE1OTE2Mzc5/NjEtNjE4OC5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/IVzeNmJjeeLUMb49S2Rq3qi4N-MbJ9qYtgoMV-_ECe0/rs:fit/g:sm/q:90/h:609/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzg5/NjQyLTE1OTE2Mzc5/NjEtNjE4OC5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/masters/1746862",
      "community": { "want": 190, "have": 3294 }
    },
    {
      "id": 7929810,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/7929810-Pop-45",
      "title": "Pop (45)",
      "thumb": "https://i.discogs.com/nI9roafkzPSdU7YeGBmNawXKRX2I9I-8fd-WcuNs2QU/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTc5Mjk4/MTAtMTU5MTI5MTUy/NS0zNzkwLnBuZw.jpeg",
      "cover_image": "https://i.discogs.com/dnLFb-iUew-HxBOqHCCD7vYAACV-D3X3MSWcJGlYmpU/rs:fit/g:sm/q:90/h:628/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTc5Mjk4/MTAtMTU5MTI5MTUy/NS0zNzkwLnBuZw.jpeg",
      "resource_url": "https://api.discogs.com/artists/7929810"
    },
    {
      "id": 3111,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/3111-Pop-Will-Eat-Itself",
      "title": "Pop Will Eat Itself",
      "thumb": "https://i.discogs.com/MUNU_YhzcfM-BFzcaZm8f47CFYLfrNYGBCrfqBW1e7U/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTMxMTEt/MTU3NDU5MjUwOS02/MzU3LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/CxdTKtd3K3biCZQqWrPIE0jdLqgbEm8MWq9P45BG7KY/rs:fit/g:sm/q:90/h:337/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTMxMTEt/MTU3NDU5MjUwOS02/MzU3LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/3111"
    },
    {
      "country": "Europe",
      "year": "1997",
      "format": ["Vinyl", "LP", "Album", "Limited Edition"],
      "label": [
        "Island Records",
        "Polygram",
        "MPO",
        "PolyGram International Music B.V.",
        "PolyGram International Music B.V.",
        "Island Records Ltd.",
        "Hanover Quay Studios",
        "Windmill Lane Studios",
        "South Beach Studios",
        "The Works, Dublin",
        "PolyGram International Music Publishing B.V.",
        "Blue Mountain Music Ltd.",
        "Mother Music",
        "Taiyo Music Inc.",
        "Masterdisk",
        "ABA, Dublin"
      ],
      "type": "release",
      "genre": ["Electronic", "Rock"],
      "style": ["Pop Rock", "Synth-pop", "Experimental"],
      "id": 726622,
      "barcode": [
        "7  31452 43341  1",
        "731452433411",
        "524 335-1",
        "524 336-1",
        "U2 10-A-1",
        "U2 10-B-1",
        "U2 10-C-1",
        "U2 10 D-1",
        "MASTERDISK",
        "BIEM/MCPS",
        "LC 0407"
      ],
      "master_id": 62553,
      "master_url": "https://api.discogs.com/masters/62553",
      "uri": "/release/726622-U2-Pop",
      "catno": "U2 10",
      "title": "U2 - Pop",
      "thumb": "https://i.discogs.com/JaKS0XqiU85dWhMUijQ2bdkJIDIEJk5EyLL0u6sWL60/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcyNjYy/Mi0xNDQwMTAzNzEy/LTQ2MzIuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/Y8HOIzj-lkTzisIrleGdaMmKCkIwuB-8Apwg3KSvW6I/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcyNjYy/Mi0xNDQwMTAzNzEy/LTQ2MzIuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/releases/726622",
      "community": { "want": 893, "have": 2441 },
      "format_quantity": 2,
      "formats": [
        {
          "name": "Vinyl",
          "qty": "2",
          "descriptions": ["LP", "Album", "Limited Edition"]
        }
      ]
    },
    {
      "id": 157382,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/157382-Pop-Levi",
      "title": "Pop Levi",
      "thumb": "https://i.discogs.com/P4evQExDbALrpJoU4ZukC0SwV5f7TMtGXS7waidivIg/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE1NzM4/Mi0xMjIxMTQ2NTA1/LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/Q3oPzDT_j4NtUmrystdiSbH-0VpnbgKhCnRf-YsmPpc/rs:fit/g:sm/q:90/h:481/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE1NzM4/Mi0xMjIxMTQ2NTA1/LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/157382"
    },
    {
      "country": "Yugoslavia",
      "year": "1976",
      "format": ["Vinyl", "LP", "Album"],
      "label": ["Jugoton", "Studio Akademik, Ljubljana", "Je\u017e, Beograd"],
      "type": "master",
      "genre": ["Jazz", "Funk / Soul"],
      "style": ["Funk", "Jazz-Funk"],
      "id": 1360397,
      "barcode": ["LYS 63055-1 ZP 14576", "LYS 63055-2 14576 ZP", "SAKOJ"],
      "master_id": 1360397,
      "master_url": "https://api.discogs.com/masters/1360397",
      "uri": "/Tihomir-Pop-Asanovi%C4%87-Pop/master/1360397",
      "catno": "LSY 63055",
      "title": "Tihomir Pop Asanovi\u0107 - Pop",
      "thumb": "https://i.discogs.com/ru9iPkR768h2MBCvWRSo-QIETCBPSVM2yUgTCsTTtoE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExODYx/MDEtMTUzMjU4OTA5/NC0yODM4LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/9oe8nSmvGHYt00rIQo0WyDPchM9grb9BFBxVHMpqIyg/rs:fit/g:sm/q:90/h:609/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExODYx/MDEtMTUzMjU4OTA5/NC0yODM4LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/masters/1360397",
      "community": { "want": 567, "have": 298 }
    },
    {
      "id": 33932,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/33932-The-Pop-Group",
      "title": "The Pop Group",
      "thumb": "https://i.discogs.com/VC9IVJOF43l3a-Mgcpb6crHo73mE2Njl-CrSdK-Glmo/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTMzOTMy/LTExNzMyOTE1NDgu/anBlZw.jpeg",
      "cover_image": "https://i.discogs.com/uQEqDYY6OS1zZr-3z5td22XulABKjtpBI_WjRWNgyRo/rs:fit/g:sm/q:90/h:381/w:548/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTMzOTMy/LTExNzMyOTE1NDgu/anBlZw.jpeg",
      "resource_url": "https://api.discogs.com/artists/33932"
    },
    {
      "id": 496887,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/496887-Dee-Pop",
      "title": "Dee Pop",
      "thumb": "https://i.discogs.com/g1m47vboJkvL-hUau7OKqEWF9K5amU8RnEh7-eKr2JU/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTQ5Njg4/Ny0xMjcyODczNDYy/LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/M0FE2o2OtcKkGbUbSBxD7BzMvJT3FMTszaSBmNbyfFo/rs:fit/g:sm/q:90/h:720/w:540/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTQ5Njg4/Ny0xMjcyODczNDYy/LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/496887"
    },
    {
      "id": 343139,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/343139-Pop-6",
      "title": "Pop (6)",
      "thumb": "https://i.discogs.com/HfG8VTos_0QpWnyn8Z949gyTZmGOCuI-HGHWymM8F1Q/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTM0MzEz/OS0xNDkyODI3NTU1/LTIwNzIuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/XkkSGVb2v0_tpB88dqXCY9O2rsLdOCc1MxjimVV-xz0/rs:fit/g:sm/q:90/h:374/w:447/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTM0MzEz/OS0xNDkyODI3NTU1/LTIwNzIuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/artists/343139"
    },
    {
      "country": "Europe",
      "year": "2016",
      "format": ["Vinyl", "LP", "Album"],
      "label": [
        "Caroline International",
        "Rekords Rekords",
        "Top Notch Booty",
        "Rancho De La Luna",
        "Pink Duck Studios",
        "United Recording Studios",
        "Pink Duck Studios",
        "Caroline International",
        "IGHO, LLC",
        "IGHO, LLC"
      ],
      "type": "release",
      "genre": ["Rock"],
      "style": ["Art Rock", "Garage Rock", "Hard Rock"],
      "id": 8258426,
      "barcode": [
        "602547778222",
        "LVR-39088-01-A  CB",
        "P.USA -38585-",
        "LVR-39088-01-B  CB ",
        "P.USA -38585-",
        "BMI",
        "[stamped]MPO\u00ae20154642[etched]CAROL-O11LP A CB   06022547778222 A",
        "[stamped]MPO\u00ae20154642[etched]CAROL-O11LP B CB   06022547778222 B",
        "[stamped]MPO\u00ae1819247[etched]CAROL-O11LP A CB   06022547778222 A",
        "[stamped]MPO\u00ae1820614[etched]CAROL-O11LP B CB   06022547778222 B"
      ],
      "master_id": 973103,
      "master_url": "https://api.discogs.com/masters/973103",
      "uri": "/release/8258426-Iggy-Pop-Post-Pop-Depression",
      "catno": "CAROLO11LP",
      "title": "Iggy Pop - Post Pop Depression",
      "thumb": "https://i.discogs.com/0SqeDepcg8oFy06d6vy8Pl2IqS36r-QXdHal1t_dsGM/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyNTg0/MjYtMTQ2MDUwNTc0/Ny0zNDc4LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/jvLckVWUdM5R6YJ2oUijVLhGLMdGeZBI2DNHL2yJ-l0/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyNTg0/MjYtMTQ2MDUwNTc0/Ny0zNDc4LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/releases/8258426",
      "community": { "want": 359, "have": 5637 },
      "format_quantity": 1,
      "formats": [
        { "name": "Vinyl", "qty": "1", "descriptions": ["LP", "Album"] }
      ]
    },
    {
      "id": 2010943,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/2010943-Icona-Pop",
      "title": "Icona Pop",
      "thumb": "https://i.discogs.com/LzJ_ad4kcYgelqteNN6A5tzil0hbD-iWPn5rDrrSh7g/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIwMTA5/NDMtMTUyMDU1Mzky/OS0zMDM5LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/nYnrB7ksF31oZIfrNCgEdg1NmOLk6flhUHAyOwVs2T4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIwMTA5/NDMtMTUyMDU1Mzky/OS0zMDM5LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/2010943"
    },
    {
      "id": 63087,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/63087-Cherry-Pop",
      "title": "Cherry Pop",
      "thumb": "https://i.discogs.com/jiuLnErkhheareSZAm3tqY2_ZTljj0aUDOPldUkNqRo/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTYzMDg3/LTEyNDEwMzUxODcu/anBlZw.jpeg",
      "cover_image": "https://i.discogs.com/IjdFT0O1eS31JiQsHuOGFotIYhgia4APaHfatlEC56Q/rs:fit/g:sm/q:90/h:147/w:160/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTYzMDg3/LTEyNDEwMzUxODcu/anBlZw.jpeg",
      "resource_url": "https://api.discogs.com/labels/63087"
    },
    {
      "id": 2383,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/2383-Baby-Pop",
      "title": "Baby Pop",
      "thumb": "https://i.discogs.com/ZXOwhaIgtOBc--Bz5tXEjMUlGFNZyqAJMtqBcZ676dw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIzODMt/MTQwMTQwMjcyMS05/MzA1LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/u8P5S5rgJODHnQDyPHE93M4evu4mjF9Rji7MbbJ6uR0/rs:fit/g:sm/q:90/h:614/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIzODMt/MTQwMTQwMjcyMS05/MzA1LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/2383"
    },
    {
      "id": 7566127,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/7566127-Pop-Smoke",
      "title": "Pop Smoke",
      "thumb": "https://i.discogs.com/OVbk8jW-4_I3lejBAOVUmx1hn07Gvj9qj1yc3oFcAwk/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTc1NjYx/MjctMTYyOTAxNTAz/Mi01MTU5LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/8f6YWYc9ER8YGS82CAN1WGV2rp20_MVqG6zjF2gr-1Y/rs:fit/g:sm/q:90/h:901/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTc1NjYx/MjctMTYyOTAxNTAz/Mi01MTU5LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/7566127"
    },
    {
      "country": "UK",
      "year": "1984",
      "format": ["Vinyl", "LP", "Album", "Stereo"],
      "label": [
        "Beggars Banquet",
        "Beggars Banquet",
        "Beggars Banquet",
        "Beggars Banquet Music Ltd.",
        "Rockfield Studios",
        "Beck Studios",
        "R.G. Jones Studios",
        "Musitech",
        "Damont",
        "WEA Records Ltd.",
        "Warner Communications"
      ],
      "type": "release",
      "genre": ["Electronic", "Rock"],
      "style": ["Goth Rock", "Pop Rock", "Synth-pop"],
      "id": 207566,
      "barcode": [
        "BEGA 51 A",
        "BEGA 51 B",
        "BEGA-51-A1. DAMONT MT.5",
        "BEGA-51-B1. DAMONT MT 5",
        "BEGA-51-A1. DAMONT MT. GA",
        "BEGA-51-B1. DAMONT MT. KA",
        "BEGA-51-A1. DAMONT MT. F",
        "BEGA-51-B1. DAMONT MT. I",
        "BEGA-51-A1. \u295f DAMONT 1 MT. E",
        "BEGA-51-B1. - DAMONT MT. J"
      ],
      "master_id": 61639,
      "master_url": "https://api.discogs.com/masters/61639",
      "uri": "/release/207566-Tones-On-Tail-Pop",
      "catno": "BEGA 51",
      "title": "Tones On Tail - Pop",
      "thumb": "https://i.discogs.com/Bf-bADbFS-oZf9hm8ghFUEa9fz5yI9YpoGgqX48otl8/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwNzU2/Ni0xMzc3MzAwNzUz/LTkxNjkuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/sZ_BHvZIYV07KWzTIZLhTq596pLCHb3r1ZqRjILyF1c/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwNzU2/Ni0xMzc3MzAwNzUz/LTkxNjkuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/releases/207566",
      "community": { "want": 823, "have": 2133 },
      "format_quantity": 1,
      "formats": [
        {
          "name": "Vinyl",
          "qty": "1",
          "descriptions": ["LP", "Album", "Stereo"]
        }
      ]
    },
    {
      "country": "Germany",
      "year": "2020",
      "format": ["Vinyl", "LP", "Album", "Limited Edition", "Stereo"],
      "label": ["twoFinger Records GmbH"],
      "type": "release",
      "genre": ["Pop"],
      "style": [],
      "id": 15389642,
      "barcode": [],
      "master_id": 1746862,
      "master_url": "https://api.discogs.com/masters/1746862",
      "uri": "/Fynn-Kliemann-POP/release/15389642",
      "catno": "none",
      "title": "Fynn Kliemann - POP",
      "thumb": "https://i.discogs.com/XULVz21K4DINqj0y0m_MP-1hkw1H71R89biuGe0a4Nc/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzg5/NjQyLTE1OTE2Mzc5/NjEtNjE4OC5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/IVzeNmJjeeLUMb49S2Rq3qi4N-MbJ9qYtgoMV-_ECe0/rs:fit/g:sm/q:90/h:609/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzg5/NjQyLTE1OTE2Mzc5/NjEtNjE4OC5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/releases/15389642",
      "community": { "want": 133, "have": 2344 },
      "format_quantity": 1,
      "formats": [
        {
          "name": "Vinyl",
          "qty": "1",
          "text": "White-Red Swirl",
          "descriptions": ["LP", "Album", "Limited Edition", "Stereo"]
        }
      ]
    },
    {
      "country": "US",
      "year": "1985",
      "format": ["Vinyl", "7\"", "45 RPM", "Single"],
      "label": [
        "Paisley Park",
        "Paisley Park",
        "Warner Bros. Records Inc.",
        "Warner Bros. Records Inc.",
        "Warner Bros. Records Inc.",
        "Warner Bros. Records Inc.",
        "Specialty Records Corporation"
      ],
      "type": "master",
      "genre": ["Rock", "Funk / Soul", "Pop"],
      "style": ["Pop Rock", "Soul", "Funk"],
      "id": 16224,
      "barcode": [
        "CCA 3342S",
        "DCA 3508S",
        "7-28998 CCA-3342-S-SRI [SRC logo] 1-1",
        "7-28998 DCA-3508-S-SRI [SRC logo] 1-2",
        "SRC(logo)"
      ],
      "master_id": 16224,
      "master_url": "https://api.discogs.com/masters/16224",
      "uri": "/master/16224-Prince-And-The-Revolution-Pop-Life",
      "catno": "9 28998-7",
      "title": "Prince And The Revolution - Pop Life",
      "thumb": "https://i.discogs.com/eAsSBU39rVwR83ULNxJITx6X6dyWAiv08MrFEKvEFYw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTkyMTUw/OTctMTQ4MDM5NzQx/NS0xNzM4LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/gNqysxMaWhbI4HB0XzJIvg0f10TZiNoZw7pXq_X9fRo/rs:fit/g:sm/q:90/h:606/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTkyMTUw/OTctMTQ4MDM5NzQx/NS0xNzM4LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/masters/16224",
      "community": { "want": 3031, "have": 7980 }
    },
    {
      "id": 2230717,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/2230717-Pop-21",
      "title": "Pop (21)",
      "thumb": "https://i.discogs.com/fpBv9bjj5iGm272_GNAmX7oS-b6odPpMGAyIV8ykNN4/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIyMzA3/MTctMTU1MTcwNTYz/MS05MjU1LnBuZw.jpeg",
      "cover_image": "https://i.discogs.com/gNJKuLTuoU2ca8AMFJ0h1wIHGSvyTgSSNkyJTdHmum8/rs:fit/g:sm/q:90/h:469/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIyMzA3/MTctMTU1MTcwNTYz/MS05MjU1LnBuZw.jpeg",
      "resource_url": "https://api.discogs.com/artists/2230717"
    },
    {
      "id": 325375,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/325375-Lolita-Pop",
      "title": "Lolita Pop",
      "thumb": "https://i.discogs.com/jCKN-MPnoMhEHExO8mf-fMWvf8SdQ43E0pWB50HyqMw/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTMyNTM3/NS0xMzMwODYyNDE4/LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/KtCUbcWLhLUAa28AnWZqBnToaog436u_sIgKVr0k2kc/rs:fit/g:sm/q:90/h:431/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTMyNTM3/NS0xMzMwODYyNDE4/LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/325375"
    },
    {
      "id": 1647643,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/1647643-Pop-1280",
      "title": "Pop. 1280",
      "thumb": "https://i.discogs.com/GC4XJkqZWBfFn6fgorHUmBkxSwnOq0W7kfbfh7d6vjs/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE2NDc2/NDMtMTU3NTYwMTg1/Ny0xNTc4LmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/rNiwbv_H6pAIgULhxsM48Pii4BRuTYDsIGRIvWZ-0Nw/rs:fit/g:sm/q:90/h:325/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE2NDc2/NDMtMTU3NTYwMTg1/Ny0xNTc4LmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/artists/1647643"
    },
    {
      "id": 387553,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/387553-Sub-Pop-2",
      "title": "Sub Pop (2)",
      "thumb": "",
      "cover_image": "https://st.discogs.com/86cc1f5820fbf8d2cf42e884012d199c7057e72a/images/spacer.gif",
      "resource_url": "https://api.discogs.com/labels/387553"
    },
    {
      "id": 2903184,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/2903184-Ingrid-Pop",
      "title": "Ingrid Pop",
      "thumb": "https://i.discogs.com/VxvonPt-a2OZR2bb-RYKTy81tLUsAAo_-UkOAOSQpUQ/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTI5MDMx/ODQtMTM2Mjg1ODYz/NS02MDI3LnBuZw.jpeg",
      "cover_image": "https://i.discogs.com/dWD_4jcE3iE7nytYhhj68ollAJPOYDuIUY__bp3X21o/rs:fit/g:sm/q:90/h:349/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTI5MDMx/ODQtMTM2Mjg1ODYz/NS02MDI3LnBuZw.jpeg",
      "resource_url": "https://api.discogs.com/artists/2903184"
    },
    {
      "id": 254537,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/254537-Sugar-Pop",
      "title": "Sugar Pop",
      "thumb": "",
      "cover_image": "https://st.discogs.com/86cc1f5820fbf8d2cf42e884012d199c7057e72a/images/spacer.gif",
      "resource_url": "https://api.discogs.com/artists/254537"
    },
    {
      "country": "US",
      "year": "1997",
      "format": ["CD", "Album"],
      "label": [
        "Island Records",
        "Island Records",
        "PMDC, USA",
        "PolyGram International Music B.V.",
        "Blue Mountain Music Ltd.",
        "Mother Music Ltd.",
        "Taiyo Music Inc.",
        "Windmill Lane Studios",
        "South Beach Studios",
        "The Works, Dublin"
      ],
      "type": "release",
      "genre": ["Electronic", "Rock"],
      "style": ["Pop Rock", "Synth-pop", "Experimental"],
      "id": 3192703,
      "barcode": [
        "73145243342 8",
        "IFPI 0393",
        "314 524 334-2 07! M 4UALKXXXX",
        "IFPI 0308",
        "14 524 334-2 07! AE 4UALKXXXX",
        "MADE IN USA BY PMDC",
        "LC0407",
        "PY811"
      ],
      "master_id": 62553,
      "master_url": "https://api.discogs.com/masters/62553",
      "uri": "/release/3192703-U2-Pop",
      "catno": "CIDU210",
      "title": "U2 - Pop",
      "thumb": "https://i.discogs.com/0vYqsP1l5UXXbxhteAOmUcaV7TAUppicgmS6dL11ZH4/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxOTI3/MDMtMTM2NjAxODgy/Mi00OTkyLmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/cZkhxRLqqe9mQ5Z8yGmPzJLKRhRb_HfiK6St1XQrmlg/rs:fit/g:sm/q:90/h:590/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxOTI3/MDMtMTM2NjAxODgy/Mi00OTkyLmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/releases/3192703",
      "community": { "want": 64, "have": 1992 },
      "format_quantity": 1,
      "formats": [{ "name": "CD", "qty": "1", "descriptions": ["Album"] }]
    },
    {
      "id": 98175,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/98175-UV-Pop",
      "title": "UV Pop",
      "thumb": "https://i.discogs.com/ddOGVV2WZqjCtdXMKoVlS81u7Evb_SnnJDggHXK5GjI/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTk4MTc1/LTE2NTE1MTM0MjIt/MjIyOS5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/v7RBb6Qs1GZNfnEat0D2QO-sW8Pq5-FotrA8lq7Zy38/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTk4MTc1/LTE2NTE1MTM0MjIt/MjIyOS5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/artists/98175"
    },
    {
      "country": "UK",
      "year": "1988",
      "format": ["Vinyl", "LP", "Album"],
      "label": [
        "Epic",
        "Native Records",
        "CBS Inc.",
        "CBS Records",
        "CBS Records",
        "CBS Music Publishing",
        "SBK Songs",
        "Greenhouse Studio, London",
        "CBS Pressing Plant, Aston Clinton",
        "CBS Records",
        "CBS Disques S.A."
      ],
      "type": "master",
      "genre": ["Rock", "Pop"],
      "style": ["Indie Pop", "Pop Rock"],
      "id": 30882,
      "barcode": [
        "5 099746 289416",
        "5099746289416",
        "462894 1a",
        "462894 1b",
        "EPC. 462 894.1.A1 POP SAID... LET'S GO TO BED :) [\u039b] ",
        "4628941 B3 POP SAID... GET OFF YOUR HEAD [\u039b]",
        "mcps/biem",
        "LC 0199",
        "CB 291",
        "PD",
        "58"
      ],
      "master_id": 30882,
      "master_url": "https://api.discogs.com/masters/30882",
      "uri": "/master/30882-The-Darling-Buds-Pop-Said",
      "catno": "462894 1",
      "title": "The Darling Buds - Pop Said...",
      "thumb": "https://i.discogs.com/DSowmd8NVa3MHPWwMx4SXX-po_y0MqIBI3DFUuqF40s/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ5OTg5/MjgtMTUyNzI2MDc3/OS01MTgwLmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/VtPom6eWwcf5ieC7DDc8WOGDNaC8TUauy0rZliVGW14/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ5OTg5/MjgtMTUyNzI2MDc3/OS01MTgwLmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/masters/30882",
      "community": { "want": 314, "have": 2364 }
    },
    {
      "id": 120799,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/120799-Pop-2",
      "title": "Pop (2)",
      "thumb": "",
      "cover_image": "https://st.discogs.com/86cc1f5820fbf8d2cf42e884012d199c7057e72a/images/spacer.gif",
      "resource_url": "https://api.discogs.com/artists/120799"
    },
    {
      "id": 398257,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/398257-Pop-Series",
      "title": "Pop Series",
      "thumb": "https://i.discogs.com/U18ePfaVqlchApOtbonPntL21jmvTLzjslVE_LRDags/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTM5ODI1/Ny0xNDQ1NDQ5NzEy/LTIyNzAuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/HhQPpYG0MC2dQpxYTmRqhcDsz3TGcs2ixNgUgnd-uD8/rs:fit/g:sm/q:90/h:270/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTM5ODI1/Ny0xNDQ1NDQ5NzEy/LTIyNzAuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/labels/398257"
    },
    {
      "id": 418444,
      "type": "label",
      "master_id": null,
      "master_url": null,
      "uri": "/label/418444-Monterey-Pop-Festival",
      "title": "Monterey Pop Festival",
      "thumb": "https://i.discogs.com/mwQ4LaO1OKNBnaCJJNYlUS-QvUG_EPh6P6gW6iCdXJA/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTQxODQ0/NC0xMzU5OTgzMjcy/LTYxMzIuanBlZw.jpeg",
      "cover_image": "https://i.discogs.com/zP7IjPM2xQyA9Kimhx3zjvht7I81Ud1rbrIjdVy14rs/rs:fit/g:sm/q:90/h:270/w:383/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTQxODQ0/NC0xMzU5OTgzMjcy/LTYxMzIuanBlZw.jpeg",
      "resource_url": "https://api.discogs.com/labels/418444"
    },
    {
      "country": "Spain",
      "year": "1980",
      "format": ["Vinyl", "LP", "Album"],
      "label": [
        "Hispavox",
        "Hispavox, S.A.",
        "Hispavox, S.A.",
        "Hispavox, S.A."
      ],
      "type": "master",
      "genre": ["Rock", "Pop"],
      "style": ["Pop Rock"],
      "id": 391376,
      "barcode": [],
      "master_id": 391376,
      "master_url": "https://api.discogs.com/masters/391376",
      "uri": "/master/391376-Nacha-Pop-Nacha-Pop",
      "catno": "S 60.499",
      "title": "Nacha Pop - Nacha Pop",
      "thumb": "https://i.discogs.com/5_jvhpPUCU-SgGaSrjd-nW7nDC-xLZNf_mLgMGDVOYY/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MTQw/OTEtMTM2MDg1NzMz/OC03MjExLmpwZWc.jpeg",
      "cover_image": "https://i.discogs.com/u3-GXkmE5Y_m15BYzji3AuXtiu1Hp6dMl-_NOpwfwUA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MTQw/OTEtMTM2MDg1NzMz/OC03MjExLmpwZWc.jpeg",
      "resource_url": "https://api.discogs.com/masters/391376",
      "community": { "want": 344, "have": 974 }
    },
    {
      "country": "Germany",
      "year": "2020",
      "format": [
        "Vinyl",
        "LP",
        "Album",
        "Limited Edition",
        "CD",
        "Album",
        "Limited Edition"
      ],
      "label": [
        "twoFinger Records GmbH",
        "SST GmbH",
        "Four Manufacturing Services",
        "HP Mastering",
        "H.O.M.E.-Studios Hamburg"
      ],
      "type": "release",
      "genre": ["Pop"],
      "style": [],
      "id": 15389716,
      "barcode": [
        "POP 0595331-A-2 FMS 200220 A2 Kr SST",
        "POP 0595331-B-2 FMS 200220 B2 Kr SST",
        "[Four Manufacturing Services logo] 57464016/FMS200420 21",
        "IFPI LP73",
        "IFPI 076Z"
      ],
      "master_id": 1746862,
      "master_url": "https://api.discogs.com/masters/1746862",
      "uri": "/release/15389716-Fynn-Kliemann-POP",
      "catno": "none",
      "title": "Fynn Kliemann - POP",
      "thumb": "https://i.discogs.com/0pmfavpYRkHjkrgkMBaVujKc4ADQ4JtjeYdJJI4_0ew/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzg5/NzE2LTE2MDU1NTk4/MTMtOTM4My5qcGVn.jpeg",
      "cover_image": "https://i.discogs.com/gyK6ioWh0ua4HuX_0Df8l5cExcOFRe6vKBZ2Tcbs01s/rs:fit/g:sm/q:90/h:609/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzg5/NzE2LTE2MDU1NTk4/MTMtOTM4My5qcGVn.jpeg",
      "resource_url": "https://api.discogs.com/releases/15389716",
      "community": { "want": 51, "have": 828 },
      "format_quantity": 2,
      "formats": [
        {
          "name": "Vinyl",
          "qty": "1",
          "text": "White-Red Swirl",
          "descriptions": ["LP", "Album", "Limited Edition"]
        },
        {
          "name": "CD",
          "qty": "1",
          "descriptions": ["Album", "Limited Edition"]
        }
      ]
    },
    {
      "country": "Germany",
      "year": "2000",
      "format": ["Vinyl", "LP", "Album"],
      "label": ["Mille Plateaux", "EFA"],
      "type": "release",
      "genre": ["Electronic"],
      "style": ["Modern Classical", "Techno", "Ambient"],
      "id": 32220,
      "barcode": ["7 18750 80831 8"],
      "master_id": 14307,
      "master_url": "https://api.discogs.com/masters/14307",
      "uri": "/Gas-Pop/release/32220",
      "catno": "MPLP 83",
      "title": "Gas - Pop",
      "thumb": "https://i.discogs.com/42QTyg8WStn_ukkf5bc_tHquma_JveudbN9aie9ceNQ/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMjIw/LTAwMS5qcGc.jpeg",
      "cover_image": "https://i.discogs.com/bYoXZg0AxJncBf-ERBHjuOdSdvImF4GOYubFTEhr0UA/rs:fit/g:sm/q:90/h:250/w:252/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMjIw/LTAwMS5qcGc.jpeg",
      "resource_url": "https://api.discogs.com/releases/32220",
      "community": { "want": 1733, "have": 515 },
      "format_quantity": 2,
      "formats": [
        { "name": "Vinyl", "qty": "2", "descriptions": ["LP", "Album"] }
      ]
    },
    {
      "id": 1882914,
      "type": "artist",
      "master_id": null,
      "master_url": null,
      "uri": "/artist/1882914-pop-X-studio",
      "title": "pop X studio",
      "thumb": "",
      "cover_image": "https://st.discogs.com/86cc1f5820fbf8d2cf42e884012d199c7057e72a/images/spacer.gif",
      "resource_url": "https://api.discogs.com/artists/1882914"
    }
  ]
}
